# -*- coding: utf-8 -*-
"""assignment -3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5LS_APzKxb3pTkq9lv2ogUTqPpMSPtP
"""

import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Load data
iris = load_iris()
X = iris.data
feature_names = iris.feature_names

# ---- Task 1: K-Means clusterig ----
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
y_pred = kmeans.fit_predict(X)

# ---- Task 2: PCA for dimensionality reduction (4D -> 2D) ----
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print(f"Explained variance ratio (PC1, PC2): {pca.explained_variance_ratio_}")
print(f"Total variance retained: {pca.explained_variance_ratio_.sum():.4f}")

# ---- Visualize clusters ----
colors = ['#e74c3c', '#3498db', '#2ecc71']
plt.figure(figsize=(7, 6))
for i in range(3):
    plt.scatter(X_pca[y_pred == i, 0], X_pca[y_pred == i, 1],
                c=colors[i], label=f'Cluster {i}', s=50, alpha=0.7, edgecolor='k')
centers_pca = pca.transform(kmeans.cluster_centers_)
plt.scatter(centers_pca[:, 0], centers_pca[:, 1], c='black', marker='X', s=200, label='Centroids')
plt.title('K-Means Clusters on Iris Dataset (PCA-reduced to 2D)')
plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% var)')
plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% var)')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('assignment_kmeans_pca.png', dpi=150, bbox_inches='tight')
print("Saved plot to assignment_kmeans_pca.png")
plt.show()