# -*- coding: utf-8 -*-
"""project -3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJHpDc0gHi40935KPZrQDkfVGjA0NV0b
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, adjusted_rand_score, accuracy_score
from scipy.stats import mode

# Load data
iris = load_iris()
X = iris.data
y_true = iris.target
target_names = iris.target_names

# PCA only used here for 2D visualization, not clustering itself
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# ---- Task 1: K-Means (k=3) ----
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
y_pred = kmeans.fit_predict(X)

# ---- Task 3: Compare predicted clusters vs true labels ----
labels_mapped = np.zeros_like(y_pred)
for cluster in range(3):
    mask = (y_pred == cluster)
    labels_mapped[mask] = mode(y_true[mask], keepdims=True)[0]

acc = accuracy_score(y_true, labels_mapped)
ari = adjusted_rand_score(y_true, y_pred)
cm = confusion_matrix(y_true, labels_mapped)

print(f"Accuracy (after label matching): {acc:.4f}")
print(f"Adjusted Rand Index: {ari:.4f}")
print(f"\nConfusion Matrix:\n{cm}")

# ---- Task 2: Visualize clusters (scatter plot), side-by-side with true labels ----
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
colors = ['#e74c3c', '#3498db', '#2ecc71']

for i in range(3):
    axes[0].scatter(X_pca[y_pred == i, 0], X_pca[y_pred == i, 1],
                     c=colors[i], label=f'Cluster {i}', s=50, alpha=0.7, edgecolor='k')
centers_pca = pca.transform(kmeans.cluster_centers_)
axes[0].scatter(centers_pca[:, 0], centers_pca[:, 1], c='black', marker='X', s=200, label='Centroids')
axes[0].set_title('K-Means Predicted Clusters')
axes[0].set_xlabel('PC1')
axes[0].set_ylabel('PC2')
axes[0].legend()
axes[0].grid(alpha=0.3)

for i, name in enumerate(target_names):
    axes[1].scatter(X_pca[y_true == i, 0], X_pca[y_true == i, 1],
                     c=colors[i], label=name, s=50, alpha=0.7, edgecolor='k')
axes[1].set_title('True Species Labels')
axes[1].set_xlabel('PC1')
axes[1].set_ylabel('PC2')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('mini_project3_clusters.png', dpi=150, bbox_inches='tight')
print("\nSaved plot to mini_project3_clusters.png")
plt.show()